/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kasir.Laporan_keuangan;
import vapestore.koneksi;
import kasir.Nota;
/**
 *
 * @author vaena
 */
public class Halaman_Kasir extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Halaman_Kasir.class.getName());
    
    private int idKasirLogin;
    private String namaKasirLogin;

    
    // Constructor baru
    // Constructor BARU (WAJIB)
    public Halaman_Kasir(int idKasir, String namaKasir) {
        this.idKasirLogin = idKasir;
        this.namaKasirLogin = namaKasir;
        initComponents();
        initCustom();
    }

    
    private void initCustom() {
        // Kosongkan tabel
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // ENTER langsung cari
        jTextField3.addActionListener(e -> jButton6ActionPerformed(null));

        // Format ribuan saat mengetik uang bayar
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formatRibuan(jTextField2);
            }
        });
    }



    /**
     * Creates new form Halaman_Kasir
     */
    
        
    // Method untuk memformat tampilan titik ribuan saat mengetik
    private void formatRibuan(javax.swing.JTextField field) {
        try {
            String original = field.getText().replaceAll("[^\\d]", "");
            if (original.isEmpty()) return;
            long nominal = Long.parseLong(original);
            String formatted = String.format(java.util.Locale.ITALY, "%,d", nominal);
            field.setText(formatted);
        } catch (Exception e) {
        }
       
    }
    
    private int simpanTransaksi(double totalHarga) throws SQLException {
        Connection conn = koneksi.getKoneksi();

    String sql = 
        "INSERT INTO transaksi (id_akun, total_harga, tanggal_transaksi) " +
        "VALUES (?, ?, NOW())";

    PreparedStatement ps = conn.prepareStatement(
        sql,
        PreparedStatement.RETURN_GENERATED_KEYS
    );

    // sementara pakai id kasir = 1
    ps.setInt(1, idKasirLogin);
    ps.setDouble(2, totalHarga);
    ps.executeUpdate();

    ResultSet rs = ps.getGeneratedKeys();
    if (rs.next()) {
        return rs.getInt(1); // id_transaksi
    }

    throw new SQLException("Gagal mendapatkan ID transaksi");
    }
    
    private void simpanDetailTransaksi(
            int idTransaksi,
            DefaultTableModel model
    ) throws SQLException {

        Connection conn = koneksi.getKoneksi();

        String sql =
            "INSERT INTO transaksi_detail " +
            "(id_transaksi, id_produk, jumlah_produk, harga_satuan, total_harga_produk, tanggal_transaksi, id_kasir) " +
            "VALUES (?, ?, ?, ?, ?, NOW(), ?)";

        PreparedStatement ps = conn.prepareStatement(sql);

        for (int i = 0; i < model.getRowCount(); i++) {

            int idProduk = Integer.parseInt(model.getValueAt(i, 0).toString());
            int jumlah   = Integer.parseInt(model.getValueAt(i, 2).toString());

            double harga = Double.parseDouble(
                model.getValueAt(i, 3).toString().replaceAll("[^0-9]", "")
            );

            double subtotal = Double.parseDouble(
                model.getValueAt(i, 4).toString().replaceAll("[^0-9]", "")
            );

            ps.setInt(1, idTransaksi);
            ps.setInt(2, idProduk);
            ps.setInt(3, jumlah);
            ps.setDouble(4, harga);
            ps.setDouble(5, subtotal);
            ps.setInt(6, idKasirLogin);

            ps.addBatch();
        }

        ps.executeBatch();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Harga :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kembalian :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Rp. 0,-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rp. 0,-");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jButton6.setText("Cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(10, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 100);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton3.setText("Riwayat Transaksi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("LogOut");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Uang Bayar :\n");

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setText("CHECKOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 420, 840, 120);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Produk", "Jumlah", "Harga", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 100, 840, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(selectedRow);
        hitungTotalHarga(); // Update total harga setelah dihapus
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hitungTotalHarga() {
    double total = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        // Ambil string lalu bersihkan dari karakter non-angka sebelum dihitung
        String val = jTable1.getValueAt(i, 4).toString().replaceAll("[^0-9]", "");
        total += Double.parseDouble(val);
    }
    // Pakai Locale.ITALY agar otomatis muncul titik pemisah ribuan
    String tampilTotal = String.format(java.util.Locale.ITALY, "%,.0f", total);
    jLabel5.setText("Rp. " + tampilTotal);
}
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String keyword = jTextField3.getText().trim();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama / kode produk dulu!");
            return;
        }

        try (Connection conn = vapestore.koneksi.getKoneksi()) {
            String sql = "SELECT id, product_name, product_price_s FROM products WHERE product_code=? OR id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, keyword);
            pst.setString(2, keyword);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("product_name");
                double harga = rs.getDouble("product_price_s");
                int qty = 1;
                
                // BUAT FORMATTER DISINI
                java.util.Locale localeID = java.util.Locale.ITALY;
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                int n = jTable1.getRowCount();
                boolean ada = false;
                
                for (int i = 0; i < n; i++) {
                    int idI = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                    if (idI == id) {
                        ada = true;
                        int jml = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
                        int newjml = jml + 1;
                        double totalT = harga * newjml;
                        
                        // Update Baris yang sudah ada dengan format titik
                        jTable1.setValueAt(newjml, i, 2);
                        jTable1.setValueAt(String.format(localeID, "%,.0f", totalT), i, 4);
                        break;
                    }
                }

                if (!ada) {
                    // Masukkan baris BARU dengan format titik
                    String hargaF = String.format(localeID, "%,.0f", harga);
                    String totalF = String.format(localeID, "%,.0f", harga * qty);
                    model.addRow(new Object[]{id, name, qty, hargaF, totalF});
                }

                hitungTotalHarga();
                jTextField3.setText(""); 
                jTextField3.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error cari barang: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Belum ada barang!");
                return;
            }

            String totalClean = jLabel5.getText().replaceAll("[^0-9]", "");
            String bayarClean = jTextField2.getText().replaceAll("[^0-9]", "");

            if (totalClean.isEmpty() || bayarClean.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data pembayaran belum lengkap!");
                return;
            }

            double totalHarga = Double.parseDouble(totalClean);
            double uangBayar = Double.parseDouble(bayarClean);

            if (uangBayar < totalHarga) {
                JOptionPane.showMessageDialog(this, "Uang pembayaran tidak cukup!");
                return;
            }

            double kembalian = uangBayar - totalHarga;
            String kembaliF = "Rp. " + String.format(java.util.Locale.ITALY, "%,.0f", kembalian);
            jLabel4.setText(kembaliF);

            // =========================
            // 1️⃣ SIMPAN TRANSAKSI
            // =========================
            int idTransaksi = simpanTransaksi(totalHarga);
            
            DefaultTableModel modelTabel =
                    (DefaultTableModel) jTable1.getModel();
            
            simpanDetailTransaksi(idTransaksi, modelTabel);

            // =========================
            // 2️⃣ BUKA NOTA
            // =========================
            Nota dialogNota = new Nota(this, true);

            dialogNota.setDataNota(
                modelTabel,
                jLabel5.getText(),
                jTextField2.getText(),
                kembaliF,
                namaKasirLogin,
                idTransaksi
            );

            dialogNota.setVisible(true);

            // =========================
            // 3️⃣ RESET KASIR
            // =========================
            modelTabel.setRowCount(0);
            jLabel5.setText("Rp. 0");
            jLabel4.setText("Rp. 0");
            jTextField2.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Checkout: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Konfirmasi logout
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Buka form login
            Admin.login1 loginForm = new Admin.login1();
            loginForm.setVisible(true);
            loginForm.pack();
            loginForm.setLocationRelativeTo(null);

            // Tutup form Halaman_Kasir saat ini
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Riwayat_transaksi riwayat =
                    new Riwayat_transaksi(idKasirLogin, namaKasirLogin);

            riwayat.setVisible(true);
            riwayat.setLocationRelativeTo(null);

            this.dispose(); // tutup Halaman_Kasir

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal membuka riwayat transaksi\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
