/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Laporan_keuangan extends javax.swing.JFrame {
    
    private JTable jTable1;
    private JLabel jLabelTotal;
}
    
    public Laporan_keuangan() {
        initComponents();
        setLocationRelativeTo(null);
        loadLaporan();
        hitungTotalPendapatan();
    }
    
    private void initComponents() {
        setTitle("Laporan Keuangan");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(800, 500);

        // ===== PANEL ATAS =====
        JPanel panelTop = new JPanel();
        panelTop.setBackground(new java.awt.Color(0, 204, 51));

        JButton btnBack = new JButton("Back");
        btnBack.addActionListener(e -> dispose());

        JLabel lblTitle = new JLabel("LAPORAN KEUANGAN");
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblTitle.setForeground(java.awt.Color.WHITE);

        panelTop.add(btnBack);
        panelTop.add(lblTitle);

        // ===== TABLE =====
        jTable1 = new JTable();
        jTable1.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Tanggal", "ID Transaksi", "Produk", "Qty", "Harga", "Subtotal"}
        ));

        JScrollPane scrollPane = new JScrollPane(jTable1);

        // ===== BOTTOM =====
        JPanel panelBottom = new JPanel();
        jLabelTotal = new JLabel("Rp. 0");
        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 16));
        panelBottom.add(new JLabel("Total Pendapatan : "));
        panelBottom.add(jLabelTotal);

        // ===== LAYOUT =====
        setLayout(new java.awt.BorderLayout());
        add(panelTop, java.awt.BorderLayout.NORTH);
        add(scrollPane, java.awt.BorderLayout.CENTER);
        add(panelBottom, java.awt.BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAPORAN KEUANGAN");

        jButton1.setText("Back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 791, 85);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nama Kasir", "Total", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 790, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadLaporan() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try (Connection conn = vapestore.koneksi.getKoneksi()) {

            String sql = """
                SELECT tanggal_transaksi, id_transaksi, id_produk, jumlah_produk, harga_satuan, total_harga_produk
                FROM transaksi_detail
                ORDER BY tanggal DESC
            """;

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            java.util.Locale localeID = java.util.Locale.ITALY;

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getDate("tangga_transaksil"),
                    rs.getString("id_transaksi"),
                    rs.getString("id_produk"),
                    rs.getInt("jumlah_produk"),
                    String.format(localeID, "%,.0f", rs.getDouble("harga")),
                    String.format(localeID, "%,.0f", rs.getDouble("subtotal"))
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat laporan: " + e.getMessage());
        }
    }

    private void hitungTotalPendapatan() {
        double total = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String val = jTable1.getValueAt(i, 5)
                .toString()
                .replaceAll("[^0-9]", "");
            total += Double.parseDouble(val);
        }

        String hasil = String.format(java.util.Locale.ITALY, "%,.0f", total);
        jLabelTotal.setText("Rp. " + hasil);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

